### PR TITLE
Add devise

### PR DESCRIPTION
**Pull request by rugwizangoga**
# Blog app: add devise

- Removed current_user method in ApplicationController.
- [Installed and setup devise](https://github.com/heartcombo/devise#getting-started).
```
Can register a new user.
User logs in with a combination of email and password.
Hashed password should be stored in the database.
Ask for confirmation of email.
Can reset password.
```
[Modified the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

### CODE REVIEW

**Review by codepantha — COMMENTED** [review]
## Hi @rugwizangoga 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 

You have submitted a project, that doesn't have code contributions from your coding partner. This is a  pair-programming activity and everybody needs to contribute to the project.



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rugwizangoga** [comment]
@codepantha is it possible for you to check for me if my PR is being reviewed caused I think it has been an hour since I submitted it for review

**Review by KDlamini — APPROVED** [review]
### Hi @rugwizangoga, @Daniel-Kigozi 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the project requirements. 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!🎊 🥳 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Devise has been installed and setup correctly
✔️  Devise is  :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, and :confirmable
✔️  The views in devise for the registration and login match the wireframes

# Status: Approved ✔️ 
 
Great-job-smiley

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rugwizangoga** [comment]
@KDlamini Thank you for the great review

**Pull request merged**
